import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langfuse import get_client
from langchain_community.callbacks import get_openai_callback

# 1. Load keys & Initialize Langfuse
load_dotenv()
langfuse = get_client()

class JudgeAgent:
    """
        The Critic.
        It takes a draft recommendation and returns a JSON score/feedback.

    """
    def __init__(self, name="Saga"):

        print(f"Initializing Judge Agent {name} ... 🤖 ⚖️")

        # The Brain
        # Initialize the generic OpenAI model.

        self.llm = ChatOpenAI(
            model="gpt-4o-mini", # Fast, smart enough and cheap
            temperature=0, # Judge should be consistent, not creative.
            api_key=os.getenv("OPENAI_API_KEY")
        )

        # The Output Parser
        # This acts like a 'translator' that forces the AI to speak in JSON
        self.parser = JsonOutputParser()


        # The Personality
        self.prompt = ChatPromptTemplate.from_messages([
            ("system", f"""
            You are a strict, skeptical Literary Critic and Fact-Checker named {name}.
            Your job is to evaluate reading recommendations generated by another AI (The Librarian).

            CRITERIA FOR EVALUATION:
            1. **Hallucination Check**: Do these books actually exist? If a title looks fake or the author is wrong, give a score of 0.
            2. **Relevance**: Does the recommendation deeply match the user's specific emotion? (e.g., If the user is 'grieving', do not recommend a generic thriller).
            3. **Laziness Check**: Penalize generic, low-effort answers (e.g., "The Alchemist" or "Harry Potter") unless they are specifically perfect for the context. We want thoughtful, curated gems.
            4. **Safety**: Ensure the content is supportive and not harmful.

            SCORING SYSTEM (0-5):
            - 5: Perfect. Insightful, real, and deeply relevant.
            - 4: Good. Relevant but maybe slightly generic.
            - 3: Acceptable but weak.
            - 0-2: Reject. Fake books, wrong authors, or completely irrelevant.

            OUTPUT FORMAT:
            You must output PURE JSON with no markdown formatting. Use this exact schema:
            {{{{
                "score": <int 0-5>,
                "feedback": "<string: brief, specific criticism or praise>"
            }}}}
            """),

            ("human", """
            USER EMOTION: {emotion}

            LIBRARIAN'S DRAFT:
            {draft}

            Evaluate this draft now.
            """)
        ])

        # The Assembler (The Chain)
        self.chain = self.prompt | self.llm | self.parser

    def evaluate(self, emotion: str, draft: str, name = "Saga") -> dict:
        """
        The public method called by the Librarian.
        Returns a dictionary: {'score': 4, 'feedback': '...'}
        """
        # Start the Main Span (The Whole Process)
        with langfuse.start_as_current_observation(
                as_type="generation", # "generation" because it's directly calling an LLM
                name="Judge Agent Evaluation",
                input={
                    "emotion": emotion, "draft": draft,}
        ) as generation:

            # Capture tokens with the callback
            with get_openai_callback() as callback:

                try:
                    print(f"⚖️⚖️ {name}, the book expert is auditing the draft ⚖️⚖️")

                    # We invoke the chain with the TWO inputs
                    result = self.chain.invoke({
                        "emotion": emotion,
                        "draft": draft
                    })

                    generation.update(
                        output=result,
                        usage={
                            "promptTokens": callback.prompt_tokens,
                            "completionTokens": callback.completion_tokens,
                            "totalTokens": callback.total_tokens
                        }
                    )

                    return result


                except Exception as e:
                    # Fallback in case of a crash
                    print(f"Judge Error: {e}")
                    generation.update(level="ERROR", status_message=str(e))
                    return {"score": 0, "feedback": "Judge crashed. Rejecting draft for safety."}

# Create the Singleton Instance
judge_agent = JudgeAgent()